server:
  port: 8585

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reportservicedb?createDatabaseIfNotExist=true
    username: root
    password: 1qaz2wsx@
    driver-class-name: com.mysql.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: create #create
    show-sql: true
    
logging:
  level:
    org:
      hibernate: 
        type: tracel
        
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8191/oauth/check_token
      
    client:
      client-id: web
      client-secret: web