server:
  port: 8585

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reportservicedb?createDatabaseIfNotExist=true
    username: root
    password: 1qaz2wsx@
    driver-class-name: com.mysql.jdbc.Driver